# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
# SPDX-FileCopyrightText: 2025 OPAL-RT Germany GmbH
# SPDX-License-Identifier: Apache-2.0
---
type: object
properties:
  extcomm:
    type: string
    default: none
    enum:
    - udp
    - tcp
    - none
    description: Type of external communication protocol helper which should be started.

  addr_framework:
    type: string
    min: 0
    max: 65535
    description: >-
      The IP address of the target on which the framework is running.

  port_framework:
    type: integer
    min: 0
    max: 65535
    description: >-
      The port on which the framework will be reachable.

  nic_framework:
    type: string
    description: >-
      The network interface that the framework will use to communicate with the client.

  nic_client:
    type: string
    description: >-
      The network interface that the client will use to communicate with the framework.

  core_framework:
    type: integer
    min: 0
    description: >-
      The core on which the tool of the framework is running. The index starts at 0.

  core_client:
    type: integer
    min: 0
    description: >-
      The core on which the tool of the client is running. The index starts at 0.
