# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
# SPDX-FileCopyrightText: 2025 OPAL-RT Germany GmbH
# SPDX-License-Identifier: Apache-2.0
---
type: object
required:
- card
- pci_index
properties:
  card:
    type: string
    example: VMIPCI5565-64M
    description: >-
      Type of reflective memory card used for a remote connection.

  pci_index:
    type: integer
    min: 1
    description: >-
      PCI index that corresponds to the communication card used for remote connection.
