# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
---

type: object
properties:
  port:
    type: integer
    default: 80
    title: Listening port
    description: |
      The TCP port number on which HTTP & WebSocket server.

  ssl_cert:
    type: string
    title: SSL Certificate Path
    description: |
      The public x509 certificate used for server-side SSL encryption.

    example: /etc/ssl/certs/mycert.pem

  ssl_private_key:
    type: string
    title: SSL Private Key Path
    description: |
      The private x509 key used for server-side SSL encryption.

    example: /etc/ssl/private/mykey.pem
